import math
print(math.pi)
print(math.e)
print("ceil",math.ceil(12.5))
print("floor",math.floor(12.6))
print("fabs",math.fabs(-12.5))
print("factorial",math.factorial(5))
print("fmod",math.fmod(11,2))
print("fsum",math.fsum([10.2,50.2,80.2]))
print("ldexp",math.ldexp(10,2)) #(x,i)---->x*(2**i)
print("modf",math.modf(11.33))
print("gcd",math.gcd(11,2))
print("trunc",math.trunc(12.5))
print("exp",math.exp(4))
print("log2",math.log2(12))
print("log10",math.log10(12))
print("pow",math.pow(10,2))
print("sqrt",math.sqrt(12))
print("cos",math.cos(12))
print("sin",math.sin(12))
print("tan",math.tan(12))
print("acos",math.acos(1))
print("asin",math.asin(1))
print("atan",math.atan(1))
print("hypot",math.hypot(12,2)) #(x**2)+(y**2)
print("degrees",math.degrees(45))
print("radians",math.radians(45))
print("copysign",math.copysign(-5.5,20))
x=float('nan')
print("isnan",math.isnan(x))
x=float('inf')
print("isinf",math.isinf(x))